'''
Created on Nov 9, 2020

@author: Derek Stoddard

test_challenges.py > Run As > Python unit-test
'''
import unittest
from qacc.challenges import Challenges


class TestChallenges(unittest.TestCase):
    def test_challenge_one(self):
        url = 'https://www.google.com/'
        result = Challenges.challenge_one(self, url)
        self.assertEqual(result, 200)  # If site is up, expect 200

    '''
    Alert Testing
    Zero generation alerts
    Alert is triggered when a monitored system does not produce energy.
    We still receive the data from the system but the generation number is zero.
    When such an alert is created, the user is notified by an email message.
    When the alert is cleared, the user is notified by email again.

    Alerts can be in one of the following states: Open, Acknowledged, or Closed.
    When an alert is first generated by the system it is in Open state.
    An email notification is sent to the user every day until the alert is Acknowledged by the user or Closed by the system.
    An Alert is Closed when the condition that caused it ceases to occur (this can happen before it is acknowledged).
    In the case of zero generation alerts, that would be when the system starts reporting energy being generated again.
    A notification email should also be sent when any alert is Closed.

    The test plan should cover both alert lifecycle and notification systems.
    
    '''

    def test_challenge_two(self):
        pass

    if __name__ == '__main__':
        unittest.main()
